# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Api Build

on:
  push:
    branches: [ main ]
# test trigger
jobs:
  build-api:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@main
        with:
          name: build.jar
          path: target/todolist-api.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: build-api
    defaults:
      run:
        working-directory: todolist-api
    steps:
      - uses: actions/download-artifact@main
        with:
          name: build.jar
          path: target/todolist-api.jar
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag todolist-api:$(date +%s)