name: Node Build

on:
  release:
    branches: [ main ]
# test trigger
jobs:
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}