name: Node Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci

  docker-build:
    runs-on: ubuntu-latest
    needs: build-ui
    defaults:
      run:
        working-directory: todolist-ui
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag todolist-ui:$(date +%s)