# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Api Publish

on:
  release:
    types: [published]
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-api:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Version
        run: |
          mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}

      - name: Commit and push version
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version ${{ env.RELEASE_VERSION }}

      - name: Build
        run: mvn -B -DskipTests package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Set Version
        run: |
          npm version ${{ env.RELEASE_VERSION }}
          git add .
          git commit -m "Set version UI: ${{ env.RELEASE_VERSION }}"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  docker-publish:
    runs-on: ubuntu-latest
    needs: build-api
    defaults:
      run:
        working-directory: todolist-api

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: todolist-api
          path: todolist-api/target/todolist-api.jar

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todolist-api:${{ env.RELEASE_VERSION }}

      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todolist-api:${{ env.RELEASE_VERSION }}